/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LanguageConfig, Patient, Prescription, AdherenceLog } from './types';

export const LANGUAGES: LanguageConfig[] = [
  {
    code: 'en',
    name: 'English',
    localName: 'English',
    greetings: {
      morning: 'Good Morning',
      afternoon: 'Good Afternoon',
      evening: 'Good Evening',
      night: 'Good Night',
    },
    labels: {
      taken: 'Taken',
      remindLater: 'Remind Later',
      medInfo: 'Medicine Info',
      vitals: 'Vitals',
      heartRate: 'Heart Rate',
      spo2: 'SpO2 Level',
      fallDetected: 'Fall Detected!',
      areYouOk: 'Are you okay?',
      emergencyTriggered: 'Emergency Triggered',
      adherence: 'Adherence',
      prescriptionWallet: 'Digital Prescriptions',
      aiHealthCard: 'Universal AI Health Card',
      timeline: 'Medicine Timeline',
      hospital: 'Hospital Portal',
      pharmacy: 'Pharmacy Portal',
      caregiver: 'Caregiver Hub',
      askAssistant: 'Ask Health Assistant...',
    },
  },
  {
    code: 'hi',
    name: 'Hindi',
    localName: 'हिन्दी',
    greetings: {
      morning: 'सुप्रभात',
      afternoon: 'नमस्कार',
      evening: 'शुभ संध्या',
      night: 'शुभ रात्रि',
    },
    labels: {
      taken: 'ले लिया',
      remindLater: 'बाद में याद दिलाएं',
      medInfo: 'दवा की जानकारी',
      vitals: 'शारीरिक संकेत',
      heartRate: 'हृदय गति',
      spo2: 'ऑक्सीजन स्तर',
      fallDetected: 'गिरावट का पता चला!',
      areYouOk: 'क्या आप ठीक हैं?',
      emergencyTriggered: 'आपातकाल सक्रिय',
      adherence: 'दवा अनुपालन',
      prescriptionWallet: 'डिजिटल पर्चे',
      aiHealthCard: 'यूनिवर्सल एआई हेल्थ कार्ड',
      timeline: 'दवा की समयरेखा',
      hospital: 'अस्पताल पोर्टल',
      pharmacy: 'फार्मेसी पोर्टल',
      caregiver: 'देखभालकर्ता डैशबोर्ड',
      askAssistant: 'स्वास्थ्य सहायक से पूछें...',
    },
  },
  {
    code: 'te',
    name: 'Telugu',
    localName: 'తెలుగు',
    greetings: {
      morning: 'శుభోదయం',
      afternoon: 'శుభ మధ్యాహ్నం',
      evening: 'శుభ సాయంత్రం',
      night: 'శుభ రాత్రి',
    },
    labels: {
      taken: 'తీసుకున్నాను',
      remindLater: 'తర్వాత గుర్తు చేయి',
      medInfo: 'మందుల సమాచారం',
      vitals: 'వైటల్స్',
      heartRate: 'గుండె వేగం',
      spo2: 'ఆక్సిజన్ స్థాయి',
      fallDetected: 'పడిపోవడం గుర్తించబడింది!',
      areYouOk: 'మీరు బాగున్నారా?',
      emergencyTriggered: 'అత్యవసర పరిస్థితి',
      adherence: 'మందుల వాడకం',
      prescriptionWallet: 'డిజిటల్ ప్రిస్క్రిప్షన్లు',
      aiHealthCard: 'యూనివర్సల్ AI హెల్త్ కార్డ్',
      timeline: 'మందుల సమయం',
      hospital: 'హాస్పిటల్ పోర్టల్',
      pharmacy: 'ఫార్మసీ పోర్タル',
      caregiver: 'సంరక్షకుని డాష్‌బోర్డ్',
      askAssistant: 'ఆరోగ్య సహాయకుడిని అడగండి...',
    },
  },
  {
    code: 'ta',
    name: 'Tamil',
    localName: 'தமிழ்',
    greetings: {
      morning: 'காலை வணக்கம்',
      afternoon: 'மதிய வணக்கம்',
      evening: 'மாலை வணக்கம்',
      night: 'இரவு வணக்கம்',
    },
    labels: {
      taken: 'எடுத்துக்கொண்டேன்',
      remindLater: 'பிறகு நினைவூட்டு',
      medInfo: 'மருந்து தகவல்',
      vitals: 'உடல் நிலைகள்',
      heartRate: 'இதய துடிப்பு',
      spo2: 'ஆக்ஸிஜன் அளவு',
      fallDetected: 'விழுதல் கண்டறியப்பட்டது!',
      areYouOk: 'நீங்கள் நலமா?',
      emergencyTriggered: 'அவசர நிலை',
      adherence: 'மருந்து கடைபிடிப்பு',
      prescriptionWallet: 'டிஜிட்டல் மருந்துச்சீட்டுகள்',
      aiHealthCard: 'யுனிவர்சல் AI ஹெல்த் கார்டு',
      timeline: 'மருந்து காலவரிசை',
      hospital: 'மருத்துவமனை போர்டல்',
      pharmacy: 'பார்மசி போர்டல்',
      caregiver: 'கவனிப்பாளர் டாஷ்போர்டு',
      askAssistant: 'சுகாதார உதவியாளரிடம் கேளுங்கள்...',
    },
  },
  {
    code: 'kn',
    name: 'Kannada',
    localName: 'ಕನ್ನಡ',
    greetings: {
      morning: 'శుభోదయ',
      afternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
      evening: 'ಶುಭ ಸಂಜೆ',
      night: 'ಶುಭ ರಾತ್ರಿ',
    },
    labels: {
      taken: 'ತೆಗೆದುಕೊಂಡಿದ್ದೇನೆ',
      remindLater: 'ನಂತರ ನೆನಪಿಸು',
      medInfo: 'ಔಷಧಿ ಮಾಹಿತಿ',
      vitals: 'ವೈಟಲ್ಸ್',
      heartRate: 'ಹೃದಯ ಬಡಿತ',
      spo2: 'ಆಮ್ಲಜನಕದ ಮಟ್ಟ',
      fallDetected: 'ಬೀಳುವಿಕೆ ಪತ್ತೆಯಾಗಿದೆ!',
      areYouOk: 'ನೀವು ಆರಾಮವಾಗಿದ್ದೀರಾ?',
      emergencyTriggered: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ',
      adherence: 'ಔಷಧಿ ಅನುಸರಣೆ',
      prescriptionWallet: 'ಡಿಜಿಟಲ್ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್',
      aiHealthCard: 'ಯುನಿವರ್ಸಲ್ AI ಹೆಲ್ತ್ ಕಾರ್ಡ್',
      timeline: 'ಔಷಧಿ ವೇಳಾಪಟ್ಟಿ',
      hospital: 'ಆಸ್ಪತ್ರೆ ಪೋರ್ಟಲ್',
      pharmacy: 'ಫಾರ್ಮಸಿ ಪೋರ್ಟಲ್',
      caregiver: 'ಪಾಲನೆದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      askAssistant: 'ಆರೋಗ್ಯ ಸಹಾಯಕರನ್ನು ಕೇಳಿ...',
    },
  },
  {
    code: 'ml',
    name: 'Malayalam',
    localName: 'മലയാളം',
    greetings: {
      morning: 'സുപ്രഭാതം',
      afternoon: 'ശുഭ മധ്യാഹ്നം',
      evening: 'ശുഭ സായാഹ്നം',
      night: 'ശുഭ രാത്രി',
    },
    labels: {
      taken: 'കഴിച്ചു',
      remindLater: 'പിന്നീട് ഓർമ്മിപ്പിക്കുക',
      medInfo: 'മരുന്ന് വിവരങ്ങൾ',
      vitals: 'വൈറ്റൽസ്',
      heartRate: 'ഹൃദയമിടിപ്പ്',
      spo2: 'ഓക്സിജൻ നില',
      fallDetected: 'വീഴ്ച കണ്ടെത്തി!',
      areYouOk: 'സുഖമാണോ?',
      emergencyTriggered: 'അടിയന്തരാവസ്ഥ',
      adherence: 'മരുന്ന് പാലനം',
      prescriptionWallet: 'ഡിജിറ്റൽ കുറിപ്പടികൾ',
      aiHealthCard: 'യൂണിവേഴ്സൽ AI ഹെൽത്ത് കാർഡ്',
      timeline: 'മരുന്ന് സമയക്രമം',
      hospital: 'ആശുപത്രി പോർട്ടൽ',
      pharmacy: 'ഫാർമസി പോർട്ടൽ',
      caregiver: 'കെയർഗിവർ ഡാഷ്‌ബോർഡ്',
      askAssistant: 'ആരോഗ്യ സഹായിയോട് ചോദിക്കുക...',
    },
  },
  {
    code: 'bn',
    name: 'Bengali',
    localName: 'বাংলা',
    greetings: {
      morning: 'সুপ্রভাত',
      afternoon: 'শুভ দুপুর',
      evening: 'শুভ সন্ধ্যা',
      night: 'শুভ রাত্রি',
    },
    labels: {
      taken: 'খেয়েছি',
      remindLater: 'পরে মনে করান',
      medInfo: 'ওষুধের তথ্য',
      vitals: 'ভাইটালস',
      heartRate: 'হৃৎস্পন্দন',
      spo2: 'অক্সিজেন মাত্রা',
      fallDetected: 'পড়ে যাওয়া সনাক্ত হয়েছে!',
      areYouOk: 'আপনি ঠিক আছেন?',
      emergencyTriggered: 'জরুরি অবস্থা সক্রিয়',
      adherence: 'ওষুধের নিয়ম মেনে চলা',
      prescriptionWallet: 'ডিজিটাল প্রেসক্রিপশন',
      aiHealthCard: 'ইউনিভার্সাল এআই হেলথ কার্ড',
      timeline: 'ওষুধের সময়সূচী',
      hospital: 'হাসপাতাল পোর্টাল',
      pharmacy: 'ফার্মেসি পোর্টাল',
      caregiver: 'কেয়ারগিভার ড্যাশবোর্ড',
      askAssistant: 'স্বাস্থ্য সহকারীকে জিজ্ঞাসা করুন...',
    },
  }
];

export const INITIAL_PATIENT: Patient = {
  id: 'AIH-882-901-IN',
  name: 'Devendra Prasad',
  age: 72,
  gender: 'Male',
  bloodGroup: 'O+',
  emergencyContactName: 'Rajesh Prasad',
  emergencyContactPhone: '+91 98765 43210',
  emergencyContactRelation: 'Son (Primary Caregiver)',
  chronicDiseases: ['Type 2 Diabetes', 'Hypertension (High Blood Pressure)'],
  allergies: ['Penicillin', 'Sulfa Drugs'],
  vitals: {
    heartRate: 72,
    spo2: 98,
    lastUpdated: 'Just now',
    isFallDetected: false,
    isEmergencyTriggered: false,
  }
};

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'PR-2026-0041',
    date: '2026-06-15',
    doctorName: 'Dr. Anjali Mehta',
    specialty: 'Cardiologist',
    hospitalName: 'Apollo Hospitals, Hyderabad',
    diagnosis: 'Primary Hypertension & Diabetic Cardioprotection',
    isFulfilled: true,
    fulfillmentDate: '2026-06-15',
    medicines: [
      {
        id: 'M-001',
        name: 'Metformin XR (500mg)',
        dosage: '1 Tablet',
        frequency: '1-0-1', // Morning, Evening
        instructions: 'After Food',
        duration: '90 Days',
        purpose: 'Lowers blood sugar levels by improving insulin sensitivity.',
        sideEffects: 'Mild nausea, stomach upset on empty stomach.',
        refillRemaining: 14,
        totalDays: 90,
        startDate: '2026-06-15',
        prescribedBy: 'Dr. Anjali Mehta',
        hospital: 'Apollo Hospitals, Hyderabad'
      },
      {
        id: 'M-002',
        name: 'Telmisartan (40mg)',
        dosage: '1 Tablet',
        frequency: '1-0-0', // Morning only
        instructions: 'Before Breakfast',
        duration: '90 Days',
        purpose: 'Relaxes blood vessels to lower blood pressure and protect kidneys.',
        sideEffects: 'Lightheadedness, dry throat.',
        refillRemaining: 18,
        totalDays: 90,
        startDate: '2026-06-15',
        prescribedBy: 'Dr. Anjali Mehta',
        hospital: 'Apollo Hospitals, Hyderabad'
      }
    ]
  },
  {
    id: 'PR-2026-0089',
    date: '2026-06-22',
    doctorName: 'Dr. S. K. Nair',
    specialty: 'Geriatric Generalist',
    hospitalName: 'Narayana Health, Bangalore',
    diagnosis: 'Mild Osteoarthritis & Calcium Deficiency',
    isFulfilled: false,
    medicines: [
      {
        id: 'M-003',
        name: 'Calcium + Vitamin D3',
        dosage: '1 Capsule',
        frequency: '0-1-0', // Afternoon only
        instructions: 'After Lunch',
        duration: '30 Days',
        purpose: 'Strengthens bones and improves calcium absorption.',
        sideEffects: 'Constipation if fluid intake is low.',
        refillRemaining: 30,
        totalDays: 30,
        startDate: '2026-06-22',
        prescribedBy: 'Dr. S. K. Nair',
        hospital: 'Narayana Health, Bangalore'
      },
      {
        id: 'M-004',
        name: 'Glucosamine Sulfate (500mg)',
        dosage: '1 Tablet',
        frequency: '0-0-1', // Night only
        instructions: 'After Dinner',
        duration: '30 Days',
        purpose: 'Supports joint cartilage health and reduces knee pain.',
        sideEffects: 'Mild digestive gas.',
        refillRemaining: 30,
        totalDays: 30,
        startDate: '2026-06-22',
        prescribedBy: 'Dr. S. K. Nair',
        hospital: 'Narayana Health, Bangalore'
      }
    ]
  }
];

export const INITIAL_ADHERENCE_LOGS: AdherenceLog[] = [
  // Yesterday's logs (100% completed)
  { id: 'l-001', date: '2026-06-27', timeSlot: 'Morning', medicineId: 'M-001', medicineName: 'Metformin XR (500mg)', status: 'Taken', timestamp: '08:15 AM' },
  { id: 'l-002', date: '2026-06-27', timeSlot: 'Morning', medicineId: 'M-002', medicineName: 'Telmisartan (40mg)', status: 'Taken', timestamp: '07:45 AM' },
  { id: 'l-003', date: '2026-06-27', timeSlot: 'Afternoon', medicineId: 'M-003', medicineName: 'Calcium + Vitamin D3', status: 'Taken', timestamp: '01:40 PM' },
  { id: 'l-004', date: '2026-06-27', timeSlot: 'Evening', medicineId: 'M-001', medicineName: 'Metformin XR (500mg)', status: 'Taken', timestamp: '08:22 PM' },
  { id: 'l-005', date: '2026-06-27', timeSlot: 'Evening', medicineId: 'M-004', medicineName: 'Glucosamine Sulfate (500mg)', status: 'Taken', timestamp: '08:30 PM' },

  // Today's logs (in progress)
  { id: 'l-006', date: '2026-06-28', timeSlot: 'Morning', medicineId: 'M-001', medicineName: 'Metformin XR (500mg)', status: 'Taken', timestamp: '08:10 AM' },
  { id: 'l-007', date: '2026-06-28', timeSlot: 'Morning', medicineId: 'M-002', medicineName: 'Telmisartan (40mg)', status: 'Taken', timestamp: '07:55 AM' },
  { id: 'l-008', date: '2026-06-28', timeSlot: 'Afternoon', medicineId: 'M-003', medicineName: 'Calcium + Vitamin D3', status: 'Pending' },
  { id: 'l-009', date: '2026-06-28', timeSlot: 'Evening', medicineId: 'M-001', medicineName: 'Metformin XR (500mg)', status: 'Pending' },
  { id: 'l-010', date: '2026-06-28', timeSlot: 'Evening', medicineId: 'M-004', medicineName: 'Glucosamine Sulfate (500mg)', status: 'Pending' },
];
